server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://localhost:3306/ontrack_user_db'
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


